### ISSUE TITLE
actionlint

### ISSUE THREAD

**Issue by YutaGoto** [YutaGoto/airis-mock#16]
https://github.com/reviewdog/action-actionlint

```yml
name: reviewdog
on:
  - pull_request
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
```
